language: java

jdk:
  - oraclejdk8


jobs:
  - name: tests_runCI
    type: runCI
    steps:
      - OUT: tests

  - name: tests_runner_runCI
    type: deploy/manifest/runSh
    steps:
      - IN: tests
